### ISSUE TITLE
Error sending mail in version 2.0.0 installed via pip

### ISSUE THREAD

**Issue by petertambach** [pretalx/pretalx#1046]
## Problem:

After upgrading our instance from 1.1.2 to version 2.0.0 using pip, Pretalx doesn't send mail anymore.
In order to verify if the problem only exists after an update, I have also installed a new instance, and the same behaviour occurs.

Executing the following command:
```python -m pretalx sendtestemail some@addr.ess```
gives the following error:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2.0.0                                                       ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                                  ┃
┃ ┃  │  O │  ┃  Database:  pretalx_localdev (mysql)                                  ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/pretalx/data/logs                                    ┃
┃ ┃  └─┘     ┃  Root dir:  /var/pretalx/venv/lib64/python3.6/site-packages/pretalx   ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /var/pretalx/venv/bin/python                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretalx/venv/lib64/python3.6/site-packages/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/management/commands/sendtestemail.py", line 33, in handle
    recipient_list=kwargs['email'],
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/mail/__init__.py", line 55, in send_mail
    fail_silently=fail_silently,
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/var/pretalx/venv/lib64/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pretalx_com'
```

Searching for ```pretalx_com```, I've found a file called ```override_settings.py``` in the ```site-packages/pretalx``` directory that overrides ```EMAIL_BACKEND```

# Solution for this problem as implemented:
Delete the file ```override_settings.py``` which is part of the ```pretalx-2.0.0.tar.gz``` archive on PyPI

**Comment by rixx** [comment]
This appears to be an erroneous `MANIFEST.in` that apparently `check-manifest` didn't catch. Thank you for reporting the issue! I'm releasing v2.1.0 (two new features, two bugfixes) right now.

I've also made a note in our [release documentation](https://docs.pretalx.org/en/latest/maintainer/release.html) to always run `check-manifest` locally before releasing a new pretalx version to prevent this problem in the future.

**Comment by rixx** [comment]
pretalx v2.1.1 is released with a fix for the issue – sorry for the inconvenience and thank you again for reporting the problem.
