### ISSUE TITLE
Make reviews unique per (user+proposal)

### ISSUE THREAD

**Issue by omercnet** [pretalx/pretalx#1098]
## Current Behavior
Getting error 500

## Expected Behavior
See reviews

## Steps to Reproduce

1. Login as specific user
1. GET reviews

## Context
Only happens with one specific user

## Your Environment

* Version used: 2.1.1
* Environment name and version (e.g. Chrome 39, python 3.5): pretalx-docker, any browser
* Operating System and version (desktop or mobile): Desktop
* Link to your instance, if in production: https://cfp.bsidestlv.com/

```
DEBUG 2021-04-11 11:57:28,833 rules predicates Testing (can_change_submissions | is_reviewer)
DEBUG 2021-04-11 11:57:28,834 rules predicates   can_change_submissions = True
DEBUG 2021-04-11 11:57:28,834 rules predicates   (can_change_submissions | is_reviewer) = True
ERROR 2021-04-11 11:57:28,902 django.request log Internal Server Error: /orga/event/bsidestlv-2021/reviews/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (1242, 'Subquery returns more than 1 row')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "/pretalx/src/pretalx/orga/views/review.py", line 78, in get_queryset
    for submission in queryset:
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
django.db.utils.OperationalError: (1242, 'Subquery returns more than 1 row')
```

**Comment by rixx** [comment]
Huh, very weird, I haven't seen that one before. Have you done anything special with your review settings?

**Comment by omercnet** [comment]
not even sure what settings I can change.. it's the third year we're using pretalx and first time we had this issue

**Comment by rixx** [comment]
Does this happen every time you open the review page?

Review settings include possible scores, score categories, and review phases with their specific settings. A lot has changed there recently, but I've never seen this error on pretalx.com.

**Comment by omercnet** [comment]
yes - consistent, but only for a specific user

what setting would reflect only on a specific user?

**Comment by omercnet** [comment]
tried meddling with some of the review settings - no change

https://github.com/pretalx/pretalx/blob/v2.1.1/src/pretalx/orga/views/review.py#L68-L70
iiuc this is the problematic subquery

**Comment by rixx** [comment]
Apparently one user managed to create two reviews for a single submission, which breaks logic :(

**Comment by omercnet** [comment]
awesome, that fixed it!!

user must have had connection issues or hit refresh too many times, submission times were a few seconds apart

but this shouldn't be possible.. this makes me concerned about CSRF..

let me know if you'd like any help followup on this through our deployment, closing this for now,

**Comment by rixx** [comment]
CSRF isn't rotated on every request (but it is required for all POST data, don't worry).

I think the right way forward is to guarantee uniqueness on a database level. That will require a migration to clean up data like in this case, so it's not just a one-line fix, regrettably. I'll keep this issue open to keep context for it.

**Comment by rixx** [comment]
Thank you for the detailed report and the understanding – a fix for this will land in the next release.
