### ISSUE TITLE
500 error on clicking Content inside Review proposal

### ISSUE THREAD

**Issue by gershbn** [pretalx/pretalx#1141]
## Current Behavior
A member with "Is a reviewer" only permission, accesses proposal from Review form. Displayed form has 2 tabs: Content and Reviews. When clicking on Content tab an internal error is displayed. The following error shows in the log:
```ERROR 2021-07-21 04:56:39,273 django.request log Internal Server Error: /orga/event/cppnorth2022/submissions/9UEBWB/
Traceback (most recent call last):
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/bootstrap4/templatetags/bootstrap4.py", line 627, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/bootstrap4/forms.py", line 39, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/var/pretalx/.local/lib/python3.6/site-packages/bootstrap4/renderers.py", line 84, in render
    return mark_safe(self._render())
  File "/var/pretalx/.local/lib/python3.6/site-packages/bootstrap4/renderers.py", line 515, in _render
    html = self.field.as_widget(attrs=self.widget.attrs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/forms/boundfield.py", line 90, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/forms/boundfield.py", line 225, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/forms/boundfield.py", line 214, in initial
    data = self.form.get_initial_for_field(self.field, self.name)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/forms/forms.py", line 489, in get_initial_for_field
    value = value()
TypeError: __call__() missing 1 required keyword-only argument: 'manager'
```

## Expected Behavior
Expected to see the proposal page

## Steps to Reproduce

1. Create a team of Reviewers with a member having only "Is a reviewer" permissions
2. Configure blind phase for proposals
3. Create a proposal
3. Login as a reviewer
4. Click on Review option on a side bar
5. Select a proposal
6. Click on Content
7. Internal Error page should show up

I also see the same error when clicking on Proposals side bar option and then trying to view one of the proposals.

## Your Environment

* Version used: 2.1.1 installed with pip3
* Ubuntu 18.04
* Python 3.6
* Chromium and Chrome

**Comment by rixx** [comment]
Hmm, I vaguely remember fixing this, but I can't find a related commit right now. I'm planning to release a new pretalx version by the end of the month (since I'm gone for a week now, that's as fast as I can manage), and I hope that the new version will resolve the issue.

If you need a fix urgently, you could try upgrading to the current master branch version (instructions [here](https://docs.pretalx.org/administrator/maintenance.html#installing-a-commit-or-a-branch-version)), though please be warned that downgrading again will require you to roll back your database to a backup taken before the upgrade.

**Comment by rixx** [comment]
Please re-open if this issue is still present with pretalx 2.2.0!
