### ISSUE TITLE
`Post-processing 'agenda/js/pretalx-schedule.js' failed!` when running `python -m pretalx rebuild`

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1517]
### Problem and impact

When running `/opt/pretalx/venv/bin/python -m pretalx rebuild`, the rebuild stops due to the above error. I cannot determine if everything else gets rebuilt properly, but as far as i can see everything looks okay.

```
[pb-11.smedia.pretalx-test][/opt/pretalx/src] > PRETALX_CONFIG_FILE=/opt/pretalx/pretalx.cfg /opt/pretalx/venv/bin/python -m pretalx rebuild
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2.3.2post0                                                                                   ┃
┃ ┃  ┌─·──╮  ┃  Settings:                                                                                             ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)                                                                       ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/pretalx/data/logs                                                                     ┃
┃ ┃  └─┘     ┃  Root dir:  /opt/pretalx/src/src/pretalx                                                               ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /opt/pretalx/venv/bin/python                                                               ┃
┃     ╰─╯       Plugins:   pretalx_venueless, pretalx_broadcast_tools, pretalx_proposal_redirects, pretalx_youtube,   ┃
┃                          pretalx_halfnarp                                                                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
File “/opt/pretalx/src/src/pretalx/locale/zh_TW/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/ar/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/pt_PT/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/de_DE/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/pt_BR/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/es_MX/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/ca/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/ja_JP/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/de_Formal/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/el/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/fr_FR/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/id/LC_MESSAGES/django.po” is already compiled and up to date.
File “/opt/pretalx/src/src/pretalx/locale/zh_CN/LC_MESSAGES/django.po” is already compiled and up to date.
Post-processing 'agenda/js/pretalx-schedule.js' failed!

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/pretalx/src/src/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/pretalx/src/src/pretalx/common/management/commands/rebuild.py", line 31, in handle
    call_command(
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/opt/pretalx/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'agenda/js/popper.js.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fb03628d090>.

The JS file 'agenda/js/pretalx-schedule.js' references a file which could not be found:
  agenda/js/popper.js.map

Please check the URL references in this JS file, particularly any
relative paths which might be pointing to the wrong location.
```

### Expected behaviour

Rebuilding succeeds without an error

### Steps to reproduce

1.
2.
3.
4.

### Operating system, dependency versions

python 3.10.6 - ubuntu 22.04

### Version

git 97a29011f7cf9845978686c7b54d03a554f64a11

**Comment by rixx** [comment]
Yeah, the pretalx build is currently failing on `main`. Don't think we need a separate issue for this tbh – having a green build is definitely a goal anyway ;)

**Comment by rixx** [comment]
Build should be running again, following pretalx/schedule@e879bf9
