### ISSUE TITLE
Build error on Ubuntu Server 22.04

### ISSUE THREAD

**Issue by jmrohwer** [pretalx/pretalx#1659]
### Problem and impact

I am trying to build pretalx on a fresh installation of Ubuntu server 22.04, according to the documentation [here](https://docs.pretalx.org/en/latest/administrator/installation.html#) which was followed step by step. This is running on a test server in a virtual machine to test the setup. I am running MariaDB as database and Apache 2 as web server as those are already installed and in use on the production server. All DEB packages are updated to their latest versions.

During [Step 5 Installation](https://docs.pretalx.org/en/latest/administrator/installation.html#step-5-installation), specifically with the command `python -m pretalx rebuild`, the build fails. The traceback is included below under Screenshots. I can continue with the process and actually start the service but when trying to access the server, I get "Internal Server error". Log from `journalctl` is also pasted below in Screenshots.

*Question*:    
Is Ubuntu 22.04 too old, specifically the version of npm shipped with Ubuntu?

### Expected behaviour

The compile should complete without error.

Incidentally, I have tried to build older versions, and the most recent version that built successfully is version 2.3.2. However, when trying to run that from the browser, it gave me a communication error:
```
Bad request.
It looks as if the communication between you and pretalx went wrong in some way.
Please return to the last page and try again!
HTTP 400
```
The log from `journalctl` then reads:
```
an 26 15:37:35 myserver gunicorn[8277]: /var/pretalx/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
Jan 26 15:37:35 myserver gunicorn[8277]:   warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Jan 26 15:37:35 myserver gunicorn[8279]: /var/pretalx/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
Jan 26 15:37:35 myserver gunicorn[8279]:   warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Jan 26 15:37:35 myserver gunicorn[8278]: /var/pretalx/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
Jan 26 15:37:35 myserver gunicorn[8278]:   warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Jan 26 15:37:52 myserver gunicorn[8277]: WARNING 2024-01-26 13:37:52,024 django.request log Bad Request: /
```
I'm assuming some of the installed Python packages are too new because of the eager upgrade strategy used by pip.

### Steps to reproduce

1. Described above in detail

### Screenshots

Compile error traceback with pretalx 2023.1.3:   
`$ python -m pretalx rebuild`
```python
523 static files copied to '/var/pretalx/static', 1017 post-processed.

> @pretalx/schedule-editor@0.0.0 build
> vite build

file:///var/pretalx/.local/lib/python3.10/site-packages/pretalx/frontend/schedule-editor/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/pretalx/.local/lib/python3.10/site-packages/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/var/pretalx/.local/lib/python3.10/site-packages/pretalx/common/management/commands/rebuild.py", line 54, in handle
    subprocess.check_call(["npm", "run", "build"], cwd=frontend_dir, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1.
```

Journalctl log when starting the service and trying to access the root of the server:
`$ sudo journalctl -u pretalx-web.service`
```
Jan 25 22:37:41 myserver gunicorn[20601]: ┃ ┏━━━━━━━━━━┓  pretalx v2023.1.3                                                     ┃
Jan 25 22:37:41 myserver gunicorn[20601]: ┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                                   ┃
Jan 25 22:37:41 myserver gunicorn[20601]: ┃ ┃  │  O │  ┃  Database:  pretalx (mysql)                                            ┃
Jan 25 22:37:41 myserver gunicorn[20601]: ┃ ┃  │ ┌──╯  ┃  Logging:   /var/pretalx/data/logs                                     ┃
Jan 25 22:37:41 myserver gunicorn[20601]: ┃ ┃  └─┘     ┃  Root dir:  /var/pretalx/.local/lib/python3.10/site-packages/pretalx   ┃
Jan 25 22:37:41 myserver gunicorn[20601]: ┃ ┗━━━┯━┯━━━━┛  Python:    /usr/bin/python3                                           ┃
Jan 25 22:37:41 myserver gunicorn[20601]: ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Jan 25 23:02:03 myserver gunicorn[20600]: WARNING 2024-01-25 21:02:03,627 pretalx.common.templatetags.vite vite Error reading vite manifest at /var/pretalx/static/pretalx-manifest.json: [Errno 2] No such file or directory: '/var/pretalx/static/pretalx-manifest.json'
Jan 25 23:02:03 myserver gunicorn[20600]: [2024-01-25 21:02:03 +0000] [20600] [ERROR] Error handling request /
Jan 25 23:02:03 myserver gunicorn[20600]: Traceback (most recent call last):
Jan 25 23:02:03 myserver gunicorn[20600]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
Jan 25 23:02:03 myserver gunicorn[20600]:     response = get_response(request)
Jan 25 23:02:03 myserver gunicorn[20600]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
Jan 25 23:02:03 myserver gunicorn[20600]:     response = self.process_request(request)
Jan 25 23:02:03 myserver gunicorn[20600]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
Jan 25 23:02:03 myserver gunicorn[20600]:     host = request.get_host()
Jan 25 23:02:03 myserver gunicorn[20600]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
Jan 25 23:02:03 myserver gunicorn[20600]:     raise DisallowedHost(msg)
...skipping...
Jan 26 15:43:21 myserver gunicorn[10992]:             <link rel="stylesheet" type="text/x-scss" href="/static/common/scss/error.7b59bf8eea45.scss"/>
Jan 26 15:43:21 myserver gunicorn[10992]:         
Jan 26 15:43:21 myserver gunicorn[10992]: During handling of the above exception, another exception occurred:
Jan 26 15:43:21 myserver gunicorn[10992]: Traceback (most recent call last):
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 135, in handle
Jan 26 15:43:21 myserver gunicorn[10992]:     self.handle_request(listener, req, client, addr)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
Jan 26 15:43:21 myserver gunicorn[10992]:     respiter = self.wsgi(environ, resp.start_response)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
Jan 26 15:43:21 myserver gunicorn[10992]:     response = self.get_response(request)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
Jan 26 15:43:21 myserver gunicorn[10992]:     response = self._middleware_chain(request)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
Jan 26 15:43:21 myserver gunicorn[10992]:     response = response_for_exception(request, exc)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
Jan 26 15:43:21 myserver gunicorn[10992]:     response = handle_uncaught_exception(
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 185, in handle_uncaught_exception
Jan 26 15:43:21 myserver gunicorn[10992]:     return callback(request)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/pretalx/common/views.py", line 148, in handle_500
Jan 26 15:43:21 myserver gunicorn[10992]:     return HttpResponseServerError(template.render(context))
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.template.render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
Jan 26 15:43:21 myserver gunicorn[10992]:     return self._render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.nodelist.render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
Jan 26 15:43:21 myserver gunicorn[10992]:     return SafeString("".join([node.render_annotated(context) for node in self]))
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
Jan 26 15:43:21 myserver gunicorn[10992]:     return SafeString("".join([node.render_annotated(context) for node in self]))
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
Jan 26 15:43:21 myserver gunicorn[10992]:     return compiled_parent._render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.nodelist.render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
Jan 26 15:43:21 myserver gunicorn[10992]:     return SafeString("".join([node.render_annotated(context) for node in self]))
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
Jan 26 15:43:21 myserver gunicorn[10992]:     return SafeString("".join([node.render_annotated(context) for node in self]))
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.render(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 160, in render
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.render_compressed(
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 106, in render_compressed
Jan 26 15:43:21 myserver gunicorn[10992]:     return self.render_offline(context)
Jan 26 15:43:21 myserver gunicorn[10992]:   File "/var/pretalx/.local/lib/python3.10/site-packages/compressor/templatetags/compress.py", line 84, in render_offline
Jan 26 15:43:21 myserver gunicorn[10992]:     raise OfflineGenerationError(
Jan 26 15:43:21 myserver gunicorn[10992]: compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "e9d8d9358cca7d47553fef69f9c8c741665c14b88d88939474ffaa47215126f1" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:
Jan 26 15:43:21 myserver gunicorn[10992]:             <link rel="stylesheet" type="text/x-scss" href="/static/common/scss/error.7b59bf8eea45.scss"/>
Jan 26 15:43:21 myserver gunicorn[10992]:         
```

### Link

n/a

### Operating system, dependency versions

Ubuntu server 22.04

### Version

2023.1.3

**Comment by rixx** [comment]
All errors you're seeing come down to the frontend file build failing. We haven't documented the required nodejs version (I'll fix that and then close this issue), but as Ubuntu 22.04 seems to ship with nodejs v12.x, it's safe to assume that that's far too old, yes, as the current version is v21.5.0.

You'll probably want to use `nvm` or an alternate `PPA` instead.
