### ISSUE TITLE
schedule.xml and schedule.json return 404 // ValueError: badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by moepman** [pretalx/pretalx#1696]
### Problem and impact

When accessing schedule.xml or schedule.json 404 is returned

In addition the following stacktrace comes up when I try to access `schedule/export/schedule.xml`:

```
ERROR 2024-02-25 11:47:45,902 pretalx.agenda.views.schedule schedule Failed to use schedule.xml for eh
Traceback (most recent call last):
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'TalkSlot' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pretalx/venv/lib/python3.11/site-packages/pretalx/agenda/views/schedule.py", line 115, in get
    file_name, file_type, data = exporter.render()
                                 ^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/pretalx/schedule/exporters.py", line 126, in render
    content = get_template("agenda/schedule.xml").render(context=context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/pretalx/schedule/models/slot.py", line 181, in uuid
    INSTANCE_IDENTIFIER = GlobalSettings().get_instance_identifier()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pretalx/venv/lib/python3.11/site-packages/pretalx/common/models/settings.py", line 28, in get_instance_identifier
    INSTANCE_IDENTIFIER = uuid.UUID(instance_identifier)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```

### Steps to reproduce

1. wget $baseurl/schedule/export/schedule.xml

### Version

v2023.1.3

**Comment by LeaRain** [comment]
To introduce a little bit more context, we investigate the issue with other export options. We are able to use `schedule.xcal` as well as ical. The admin functionality for exporting the program with CSV and JSON seems to be working properly. However, the public information for the schedule with XML and JSON is broken

**Comment by rixx** [comment]
This bug was fixed a while ago and the fix is released in pretalx v2024.1.0 – please update to the current release before opening bug reports if at all possible (to cut down on investigation time in cases like this).
