### ISSUE TITLE
Error message: Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits

### ISSUE THREAD

**Issue by saschafoerster** [pretalx/pretalx#1865]
### Problem and impact

After the start, I get this error message and I don't now how to fix. :) 

` Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits`

```
pretalx  | ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
pretalx  | ┃ ┏━━━━━━━━━━┓  pretalx v2024.3.0                                                                                    ┃
pretalx  | ┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                                                                  ┃
pretalx  | ┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)                                                                      ┃
pretalx  | ┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                                                                                ┃
pretalx  | ┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3                                                                    ┃
pretalx  | ┃ ┗━━━┯━┯━━━━┛  Source:    /pretalx/src/pretalx                                                                      ┃
pretalx  | ┃     ╰─╯       Plugins:   pretalx_broadcast_tools, pretalx_pages, pretalx_venueless, prtx_faq, pretalx_socialauth   ┃
pretalx  | ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
pretalx  | Operations to perform:
pretalx  |   Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, pretalx_pages, pretalx_venueless, prtx_faq, schedule, sessions, submission
pretalx  | Running migrations:
pretalx  | Traceback (most recent call last):
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in _execute
pretalx  |     return self.cursor.execute(sql)
pretalx  | psycopg2.errors.DuplicateColumn: FEHLER:  Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits
pretalx  | 
pretalx  | 
pretalx  | The above exception was the direct cause of the following exception:
pretalx  | 
pretalx  | Traceback (most recent call last):
pretalx  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
pretalx  |     return _run_code(code, main_globals, None,
pretalx  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
pretalx  |     exec(code, run_globals)
pretalx  |   File "/pretalx/src/pretalx/__main__.py", line 9, in <module>
pretalx  |     execute_from_command_line(sys.argv)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
pretalx  |     utility.execute()
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
pretalx  |     self.fetch_command(subcommand).run_from_argv(self.argv)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
pretalx  |     self.execute(*args, **cmd_options)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
pretalx  |     output = self.handle(*args, **options)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
pretalx  |     res = handle_func(*args, **kwargs)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 357, in handle
pretalx  |     post_migrate_state = executor.migrate(
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
pretalx  |     state = self._migrate_all_forwards(
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
pretalx  |     state = self.apply_migration(
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
pretalx  |     state = migration.apply(state, schema_editor)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
pretalx  |     operation.database_forwards(
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards
pretalx  |     schema_editor.add_field(
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 768, in add_field
pretalx  |     self.execute(sql, params or None)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
pretalx  |     return super().execute(sql, params)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 202, in execute
pretalx  |     cursor.execute(sql, params)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
pretalx  |     return self._execute_with_wrappers(
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
pretalx  |     return executor(sql, params, many, context)
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
pretalx  |     with self.db.wrap_database_errors:
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
pretalx  |     raise dj_exc_value.with_traceback(traceback) from exc_value
pretalx  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in _execute
pretalx  |     return self.cursor.execute(sql)
pretalx  | django.db.utils.ProgrammingError: FEHLER:  Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits
pretalx  | 
pretalx  |   Applying person.0028_user_avatar_thumbnail_user_avatar_thumbnail_tiny...2024-10-25 11:03:20,862 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
pretalx  | 2024-10-25 11:03:20,872 INFO RPC interface 'supervisor' initialized
pretalx  | 2024-10-25 11:03:20,872 CRIT Server 'unix_http_server' running without any HTTP authentication checking
pretalx  | 2024-10-25 11:03:20,872 INFO supervisord started with pid 10
pretalx  | 2024-10-25 11:03:21,876 INFO spawned: 'pretalxtask' with pid 11
pretalx  | 2024-10-25 11:03:21,890 INFO spawned: 'pretalxweb' with pid 12
pretalx  | 2024-10-25 11:03:22,892 INFO success: pretalxtask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pretalx  | 2024-10-25 11:03:22,893 INFO success: pretalxweb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

### Expected behaviour

No error message. 

### Steps to reproduce

I think this happened because of the migration from v.2024.2.4 to v2024.3.0 and included a migration from MariaDB to PostgreSQL.

### Operating system, dependency versions

Debian 11, Docker

### Version

pretalx v2024.3.0

**Comment by saschafoerster** [comment]
```
docker exec -it pretalx pretalx migrate
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.0                                                                                    ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                                                                  ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)                                                                      ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                                                                                ┃
┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3                                                                    ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /pretalx/src/pretalx                                                                      ┃
┃     ╰─╯       Plugins:   pretalx_broadcast_tools, pretalx_pages, pretalx_venueless, prtx_faq, pretalx_socialauth   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Operations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, pretalx_pages, pretalx_venueless, prtx_faq, schedule, sessions, submission
Running migrations:
  Applying person.0028_user_avatar_thumbnail_user_avatar_thumbnail_tiny...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateColumn: FEHLER:  Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/pretalx/src/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 768, in add_field
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 202, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: FEHLER:  Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.0                                                                                    ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                                                                  ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)                                                                      ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                                                                                ┃
┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3                                                                    ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /pretalx/src/pretalx                                                                      ┃
┃     ╰─╯       Plugins:   pretalx_broadcast_tools, pretalx_pages, pretalx_venueless, prtx_faq, pretalx_socialauth   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Operations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, pretalx_pages, pretalx_venueless, prtx_faq, schedule, sessions, submission
Running migrations:
  Applying person.0028_user_avatar_thumbnail_user_avatar_thumbnail_tiny...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateColumn: FEHLER:  Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/pretalx/src/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 768, in add_field
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 202, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: FEHLER:  Spalte »avatar_thumbnail« von Relation »person_user« existiert bereits
```

**Comment by rixx** [comment]
Sounds like something went wrong with your db migration, yes – you'll likely need to run something like `migrate --fake person 0028`, and maybe also `migrate --fake person 0029`, in order to get pretalx/django to accept that those migrations have taken place already. I don't believe that this is a general pretalx bug, though.

**Comment by saschafoerster** [comment]
First do a backup. :) 

I did: 
`docker exec -it pretalx pretalx migrate --fake person 0028`
and 
`docker exec -it pretalx pretalx migrate `
then I got: 
`django.db.utils.ProgrammingError: FEHLER:  Relation »submission_submissionfavourite« existiert bereits`
I did then: 
`docker exec -it pretalx pretalx migrate --fake submission 0076`
then this error: 
`django.db.utils.ProgrammingError: FEHLER:  Spalte »position« von Relation »submission_answeroption« existiert bereits`
so 
`docker exec -it pretalx pretalx migrate --fake submission 0077`
A new error: 
```
django.db.utils.IntegrityError: FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint »django_content_type_pkey«
DETAIL:  Schlüssel »(id)=(45)« existiert bereits.
```
I got some more similar errors after this, I just repeated: 
`docker exec -it pretalx pretalx migrate `
until finally: 
`  No migrations to apply.`
Hope this helps, in case someone has this issue.
