### ISSUE TITLE
Write user documentation

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#397]
A guide on how to set up a regular pretalx event, and an explanation of optional features like the review workflow, are sorely lacking.

Don't forget the screenshots.

**Comment by maqor** [comment]
Hello,

I would like to work on this issue, but have a few questions beforehand.

1) Has there been anything done besides the design guide ( #391 ) or do I start from scratch? (Starting from scratch is totally fine though!)
2) Should I write the documentation in English only? I can also offer a german translation (German is my mother tongue).
3) Do you have any special wishes regarding the user documentation?

Please be advised that I have little to no experience in developing software (I am familiar with git though). If that gets in the way of completing this task, please let me know.

**Comment by rixx** [comment]
Parts of the user documentation will have to intersect with development tasks: on the one hand for screenshot generation (which is easily isolated), but also on the other hand to find out what the actual behaviour to be documented is.

That said, there is plenty to be done without touching code, and I'm always happy to answer questions! I started minimal preparations so that there is at least a user guide section in the docs [now](https://docs.pretalx.org/user/index.html). 
If you want to preview the documentation on your PC, you will have to follow the developer setup guide, but you don't have to do that – every bit helps.

I was thinking to roughly follow the structure of the [pretix user guide](https://docs.pretix.eu/en/latest/user/index.html), but even that's not set in stone. Happy to take any (partial) contributions.

**Comment by maqor** [comment]
The steps in the Developer's Setup Guide seem simple enough for me to follow, and I don't think there will be any problems in doing so.

Sweet! I'll get to work then!

**Comment by maqor** [comment]
I've encountered a problem using the sphinx-autobuild feature. Both the pretalx development server and sphinx-autobuild use port 8000, leading to conflicts.

Expected behaviour:
The developer documentation (https://docs.pretalx.org/developer/setup.html#working-with-the-documentation) states, that sphinx-autobuild is available on localhost:8081. Therefore it should be possible to run both pretalx and sphinx-autobuild simultaneously.

Encountered behaviour:
Both pretalx and sphinx-autobuild run on localhost:8000, leading to the service started second throwing an "Address already in use" error.

Steps to reproduce:
1. Start pretalx development server by running `python manage.py runserver` from the src directory.
2. Open a ssecond terminal and start sphinx by running `sphinx-autobuild . _build/html` from the doc directory.
3. sphinx-autobuild gives the following error:
```
[I 220114 23:15:21 server:335] Serving on http://127.0.0.1:8000
Traceback (most recent call last):
  File "/home/andreas/Projekte/pretalx/env/bin/sphinx-autobuild", line 8, in <module>
    sys.exit(main())
  File "/home/andreas/Projekte/pretalx/env/lib64/python3.8/site-packages/sphinx_autobuild/cli.py", line 196, in main
    server.serve(port=portn, host=args.host, root=outdir)
  File "/home/andreas/Projekte/pretalx/env/lib64/python3.8/site-packages/livereload/server.py", line 339, in serve
    self.application(
  File "/home/andreas/Projekte/pretalx/env/lib64/python3.8/site-packages/livereload/server.py", line 291, in application
    app.listen(port, address=host)
  File "/home/andreas/Projekte/pretalx/env/lib64/python3.8/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/home/andreas/Projekte/pretalx/env/lib64/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/andreas/Projekte/pretalx/env/lib64/python3.8/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

**Comment by maqor** [comment]
I've encountered a problem using the sphinx-autobuild feature. Both the pretalx development server and sphinx-autobuild use port 8000, leading to conflicts.

Expected behaviour:
The developer documentation (https://docs.pretalx.org/developer/setup.html#working-with-the-documentation) states, that sphinx-autobuild is available on localhost:8081. Therefore it should be possible to run both pretalx and sphinx-autobuild simultaneously.

Encountered behaviour:
Both pretalx and sphinx-autobuild run on localhost:8000, leading to the service started second throwing an "Address already in use" error.

Steps to reproduce:
1. Start pretalx development server by running `python manage.py runserver` from the src directory.
2. Open a ssecond terminal and start sphinx by running `sphinx-autobuild . _build/html` from the doc directory.
3. sphinx-autobuild gives the following error:
```
[I 220114 23:15:21 server:335] Serving on http://127.0.0.1:8000
Traceback (most recent call last):
  File "/home/user/projects/pretalx/env/bin/sphinx-autobuild", line 8, in <module>
    sys.exit(main())
  File "/home/user/projects/pretalx/env/lib64/python3.8/site-packages/sphinx_autobuild/cli.py", line 196, in main
    server.serve(port=portn, host=args.host, root=outdir)
  File "/home/user/projects/pretalx/env/lib64/python3.8/site-packages/livereload/server.py", line 339, in serve
    self.application(
  File "/home/user/projects/pretalx/env/lib64/python3.8/site-packages/livereload/server.py", line 291, in application
    app.listen(port, address=host)
  File "/home/user/projects/pretalx/env/lib64/python3.8/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/home/user/projects/pretalx/env/lib64/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/user/projects/pretalx/env/lib64/python3.8/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

**Comment by rixx** [comment]
You'll want to add a `--port 8001` (or whatever port works best for you) to the sphinx autobuild command.

**Comment by rixx** [comment]
Hey @maqor, just wanted to check in how it's going: Do you need any assistance? Do you want to share a draft for review or collaboration?

**Comment by rixx** [comment]
WIP comment where I will dump explanations I've written in email support, in case that they are useful.

<details>
<summary>Scheduling and the schedule editor</summary>
Talks can be scheduled as soon as they have been accepted, but they will only show up in any public schedule once they have been marked as "confirmed".

Talks can be scheduled in two ways: On the talk detail page, you can enter a room and a time in the normal talk form. Or you can use the more interactive schedule editor ("schedule" in the sidebar).

In the interactive schedule editor, you can click the top of the "unassigned talks" box to hide it if you're low on space. You can also drag and hold on any room to create a "break" slot, also useful for administrative slots like events, registration and so on. You can see here how these look in practice:
https://pretalx.com/democon/schedule/

Any change you make, be it in a talk page or in the schedule editor, will *not* be public immediately, to give you some time to figure out how the schedule should look. When you are ready to finalise the first schedule (or any change later), click the "new release" button on top of the schedule editor to release a new schedule version.

The next page will show you what exactly has changed compared to the last version, and it will warn you if any speakers or rooms are unavailable at the scheduled time, or if you have double-booked a speaker. You can then confirm that you want to release this schedule version, and optionally generate notification emails for speakers. These emails will only be generated for speakers whose talk's time or room has changed. There is a template that you can use to customize those emails.

And that's pretty much it! On top of the schedule editor, there is also a button titled "actions", which includes a link to the live-preview of the current (not yet released) schedule. This page is only accessible to logged in organisers, and will show you what your schedule will look like upon release.
</details>

**Comment by rixx** [comment]
another WIP comment on the screenshots: Should look into adding a utility to add highlights/arrows to screenshots, inspired by [Simon](https://simonwillison.net/2022/Mar/10/shot-scraper/)

**Comment by rixx** [comment]
No screenshots, but otherwise done for the moment.
