### ISSUE TITLE
Unable to generate any schedules!  Version 0.9.0

### ISSUE THREAD

**Issue by mraugh** [pretalx/pretalx#808]
## Current Behavior

```
pretalx@pretalx-2:~/data/htmlexport$ python3 -m pretalx export_schedule_html charmed2020
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  This is pretalx v0.9.0 calling, running in production mode.   ┃
┃ ┃  ┌─·──╮  ┃                                                                ┃
┃ ┃  │  O │  ┃  Settings:                                                     ┃
┃ ┃  │ ┌──╯  ┃  Read from: /etc/pretalx/pretalx.cfg                           ┃
┃ ┃  └─┘     ┃  Database:  pretalx (mysql)                                    ┃
┃ ┗━━━┯━┯━━━━┛  Logging:   /var/pretalx/data/logs                             ┃
┃     ╰─╯                                                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
INFO 2019-11-10 23:12:59,071 bakery.management.commands.build build Build started
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/agenda/management/commands/export_schedule_html.py", line 63, in handle
    super().handle(*args, **options)
  File "/var/pretalx/.local/lib/python3.6/site-packages/bakery/management/commands/build.py", line 112, in handle
    self.build_views()
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/agenda/management/commands/export_schedule_html.py", line 77, in build_views
    view(_exporting_event=self._exporting_event).build_method()
  File "/var/pretalx/.local/lib/python3.6/site-packages/bakery/views/detail.py", line 72, in build_queryset
    [self.build_object(o) for o in self.get_queryset().all()]
  File "/var/pretalx/.local/lib/python3.6/site-packages/bakery/views/detail.py", line 72, in <listcomp>
    [self.build_object(o) for o in self.get_queryset().all()]
  File "/var/pretalx/.local/lib/python3.6/site-packages/bakery/views/detail.py", line 69, in build_object
    self.build_file(target_path, self.get_content())
  File "/var/pretalx/.local/lib/python3.6/site-packages/bakery/views/base.py", line 53, in get_content
    return self.get(self.request).render().content
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/agenda/views/htmlexport.py", line 29, in get_context_data
    context = super().get_context_data(*args, **kwargs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/agenda/views/schedule.py", line 140, in get_context_data
    event=self.request.event, schedule=context['schedule']
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/schedule/exporters.py", line 79, in data
    d['rooms'].values(), key=lambda room: room['position'] or room['name']
TypeError: '<' not supported between instances of 'int' and 'LazyI18nString'
pretalx@pretalx-2:~/data/htmlexport$ 
```

## Expected Behavior
A schedule gets generated.

## Steps to Reproduce

1. Open shell session
2. Change to user pretalx
3. Issue command: python3 -m pretalx export_schedule_html charmed2020
4.

## Context

I'm trying to use the application to run an event.  I have a database of 100 classes and I want to publish a schedule, and the publisher won't run.  I don't have any Python experience to speak of, so I can't make any sense out of the error output.

## Your Environment
Ubuntu 18.04 hosted in Google cloud
Pretalx 0.9.0 (I'm afraid to upgrade in the middle of an event cycle)
Python 3.6.8

* Link to your instance, if in production:
https://pretalx.charmedhypno.org

Please help, somebody.  :(

**Comment by luto** [comment]
I'm sorry to hear that :/ Luickly, this exact issue was fixed back in February:  https://github.com/pretalx/pretalx/commit/e7f9949f73727e5c039b8bde3d000ce6ba67c1b9. The Fix itself was changed a few days later in https://github.com/pretalx/pretalx/commit/7c5516015aa7cb83a0bdd9507c53bfec504efa96. Either version should fix your problem. Sooo, if you're feeling adventurous you can edit your `/var/pretalx/.local/lib/python3.6/site-packages/pretalx/schedule/exporters.py` to match or download the patch files by appending `.patch` to the above URLs.

**Comment by mraugh** [comment]
Thank you!  I feel helpless at times because I'm an old Perl/PHP guy and don't know anything about Python or Django.  That fix worked, and I learned a little more about using GitHub in the process.  

BTW, my event is called Charmed! 2020 and it's a hypnosis conference in Annapolis, MD.  This is our first year using Pretalx and I really like it.  Language is a barrier (computer language, that is), obviously, but I'd really like to help beef up the feedback area.  What's the best way to learn Python quickly?

<MR>

**Comment by rixx** [comment]
Great to hear about your experiences! I found your event a while ago and added you to [our event list](https://github.com/pretalx/pretalx/wiki/Events). Always super interesting to see what events pretalx is used for.

Regarding Python and Django, the friendliest and most available tutorial is the [DjangoGirls tutorial](http://tutorial.djangogirls.org/) which explains both Python and Django. Since you have other programming experiences already, you'll proably be able to skip some parts, but it's always nice to have a complete references.

Also, feel free to get in touch at support at pretalx.com if you want to give feedback privately or want pointers/guidance on contributions.
