### ISSUE TITLE
Migration failed: AttributeError: 'NoneType' object has no attribute 'subject'

### ISSUE THREAD

**Issue by xoxys** [pretalx/pretalx#861]
I try to upgrade a docker based pretalix v0.7 setup to latest v1.1 but the migration step failed with following traceback:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v1.1.2                                        ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                   ┃
┃ ┃  │  O │  ┃  Database:  pretalx (mysql)                            ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/lib/pretalx/logs                      ┃
┃ ┃  └─┘     ┃  Root dir:  /usr/lib/python3.6/site-packages/pretalx   ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /usr/bin/python3                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Operations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, schedule, sessions, submission
Running migrations:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/lib/python3.6/site-packages/pretalx/event/migrations/0019_auto_20190224_0856.py", line 15, in fix_update_template
    template.subject = UPDATE_SUBJECT
AttributeError: 'NoneType' object has no attribute 'subject'
  Applying event.0019_auto_20190224_0856...
```

Any suggestions what I've missed or how to fix it?

**Comment by rixx** [comment]
Hm, for some reason, this event does not have an `update_template`. You can fix this by going into the pretalx shell (`python -m pretalx shell_scoped --override`), and running these commands:

```python
event = Event.objects.get(slug="my_event_slug")
event.build_initial_data()
```

If there is a problem with the database state, you can skip this migration:

```
python -m pretalx migrate --fake event 0019
python -m pretalx migrate
```

And then run the `build_initial_data` command afterwards.

**Comment by xoxys** [comment]
Sorry but that results in another error:
```
All scopes are disabled for this shell session – please be careful!
Python 3.6.8 (default, Nov 13 2019, 07:55:59) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from pretalx.event.models import Event
>>> event = Event.objects.get(slug="my_event_slug")
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'event_event.header_image' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'event_event.header_image' in 'field list'")
```

Would it be better to upgrade step by step? E.g. v0.7.* -> v0.8.* -> ...

**Comment by rixx** [comment]
That's what I meant by the second half of the instructions, starting at "if there is a problem" – did you try that part?

**Comment by xoxys** [comment]
Yeah I've read it but was not quiet sure sorry. Migrations proceeded now but buil_initial_data failed:
```
All scopes are disabled for this shell session – please be careful!
Python 3.6.8 (default, Nov 13 2019, 07:55:59) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> event = Event.objects.get(slug="my_event_slug")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Event' is not defined
>>> from pretalx.event.models import Event
>>> event = Event.objects.get(slug="my_event_slug")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
pretalx.event.models.event.Event.DoesNotExist: Event matching query does not exist.
>>> 
```

**Comment by rixx** [comment]
You will have to replace "my_event_slug" with your actual event slug.

**Comment by xoxys** [comment]
Doesn't fix the issue... Maybe it's me but I don't get it. I have restored my working 0.7 installation and started again: 
Upgrade to v0.8 WORKS
Upgrade to v0.9 WORKS
Upgrade to v1.0 FAILED

```
> executing pretalx migrate
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1050, "Table 'submission_question_tracks' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/schema.py", line 44, in add_field
    super().add_field(model, field)
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 431, in add_field
    return self.create_model(field.remote_field.through)
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'submission_question_tracks' already exists")
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v1.0.3                                        ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                   ┃
┃ ┃  │  O │  ┃  Database:  pretalx (mysql)                            ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/lib/pretalx/logs                      ┃
┃ ┃  └─┘     ┃  Root dir:  /usr/lib/python3.6/site-packages/pretalx   ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /usr/bin/python3                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Operations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, schedule, sessions, submission
Running migrations:
  Applying submission.0031_auto_20190223_0730...> executing pretalx rebuild
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v1.0.3                                        ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                   ┃
┃ ┃  │  O │  ┃  Database:  pretalx (mysql)                            ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/lib/pretalx/logs                      ┃
┃ ┃  └─┘     ┃  Root dir:  /usr/lib/python3.6/site-packages/pretalx   ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /usr/bin/python3                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
processing file django.po in /usr/lib/python3.6/site-packages/pretalx/locale/de_DE/LC_MESSAGES
processing file django.po in /usr/lib/python3.6/site-packages/pretalx/locale/fr_FR/LC_MESSAGES

0 static files copied to '/var/lib/pretalx/static', 488 unmodified, 467 post-processed.
Compressing... done
Compressed 30 block(s) from 386 template(s) for 0 context(s).
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'event_event.header_image' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/pretalx/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/pretalx/common/management/commands/regenerate_css.py", line 26, in handle
    event = Event.objects.get(pk=es.object_id)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'event_event.header_image' in 'field list'")
```

I'm about to give up :(

**Comment by rixx** [comment]
You can always get in touch at support@pretalx.com, but from what I'm seeing here, you have not reset the database completely, and it's now in a weird and inconsistent state because you partially executed migrations – note how it says that the table "submission_question_tracks" already exists, which can only happen if you have executed migrations, then incompletely rolled back the database.

The interesting part would have been how the instructions did not fix the issue – but now that you've got the database in this inconsistent state, it will be noticeably harder to fix.

**Comment by xoxys** [comment]
I'm really sorry to bother you with this problem... I did a full reset this time, dropped the database created a fresh one imported dump and do exactly what you suggested earlier and I guess I am a huge step closer now. Migration steps finished without any error now and the server starts without any error message. I am also able to access the start page in the browser but there is an issue with the css/js files:

```
[2020-01-21 21:16:45 +0000] [981] [ERROR] Error handling request /static/CACHE/css/output.6ecb2cd991be.css
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.6/site-packages/dj_static.py", line 88, in __call__
    return self.cling(environ, start_response)
  File "/usr/lib/python3.6/site-packages/static.py", line 151, in __call__
    full_path = self._full_path(path_info)
  File "/usr/lib/python3.6/site-packages/static.py", line 198, in _full_path
    return self.root + path_info
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
[2020-01-21 21:16:45 +0000] [988] [ERROR] Error handling request /static/common/img/logo.c86a874657c9.svg
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.6/site-packages/dj_static.py", line 88, in __call__
    return self.cling(environ, start_response)
  File "/usr/lib/python3.6/site-packages/static.py", line 151, in __call__
    full_path = self._full_path(path_info)
  File "/usr/lib/python3.6/site-packages/static.py", line 198, in _full_path
    return self.root + path_info
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'[2020-01-21 21:16:45 +0000] [980] [ERROR] Error handling request /static/CACHE/js/output.5b270a5bf623.js
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.6/site-packages/dj_static.py", line 88, in __call__
    return self.cling(environ, start_response)
  File "/usr/lib/python3.6/site-packages/static.py", line 151, in __call__
    full_path = self._full_path(path_info)
  File "/usr/lib/python3.6/site-packages/static.py", line 198, in _full_path
    return self.root + path_info
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

[2020-01-21 21:16:45 +0000] [979] [ERROR] Error handling request /static/common/scss/uncompressed.ec8d16cc3696.css
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.6/site-packages/dj_static.py", line 88, in __call__
    return self.cling(environ, start_response)
  File "/usr/lib/python3.6/site-packages/static.py", line 151, in __call__
    full_path = self._full_path(path_info)
  File "/usr/lib/python3.6/site-packages/static.py", line 198, in _full_path
    return self.root + path_info
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

Thank you very much for your time!

**Comment by xoxys** [comment]
I was able to fix it with a small change in `/usr/lib/python3.6/site-packages/static.py` I have just string cast `str(self.root)` in _full_path function and now it works but I guess that's not the real root cause, right?

**Comment by rixx** [comment]
I haven't seen this error before, so I can only speculate, but it seems like you are running pretalx  `dj_static` installed, which is not part of the recommended pretalx install process. I'd recommend uninstalling `dj_static` for now – it seems they can't cope with PosixPath, which pretalx uses heavily for file system navigation.

**Comment by xoxys** [comment]
Thanks again! It works now
