### ISSUE TITLE
Creation invite leads to redis missing bug

### ISSUE THREAD

**Issue by pathetiq** [pretalx/pretalx#993]
## Current Behavior

When I invite a user to a team (orga/organiser/USERNAME/teams/2/) I got an error 500 with the following error in the logs:

```
ERROR 2020-08-25 12:50:35,647 django.request log Internal Server Error: /orga/organiser/PathetiQ/teams/2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Django-2.2.15-py3.6.egg/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.2.15-py3.6.egg/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.2.15-py3.6.egg/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.2.15-py3.6.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.2.15-py3.6.egg/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.2.15-py3.6.egg/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/orga/views/organiser.py", line 71, in post
    invite.send(event=None)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/event/models/organiser.py", line 196, in send
    mail.send()
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/mail/models.py", line 270, in send
    "bcc": (self.bcc or "").split(","),
  File "/usr/local/lib/python3.6/dist-packages/celery-4.3.0-py3.6.egg/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python3.6/dist-packages/celery-4.3.0-py3.6.egg/celery/app/base.py", line 752, in send_task
    with self.producer_or_acquire(producer) as P:
  File "/usr/local/lib/python3.6/dist-packages/celery-4.3.0-py3.6.egg/celery/utils/objects.py", line 86, in __enter__
    *self.fb_args, **self.fb_kwargs
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/resource.py", line 83, in acquire
    R = self.prepare(R)
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/pools.py", line 62, in prepare
    p = p()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/utils/functional.py", line 210, in __call__
    return self.evaluate()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/utils/functional.py", line 213, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/pools.py", line 42, in create_producer
    conn = self._acquire_connection()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/pools.py", line 39, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/resource.py", line 83, in acquire
    R = self.prepare(R)
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/connection.py", line 1010, in prepare
    resource = resource()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/utils/functional.py", line 210, in __call__
    return self.evaluate()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/utils/functional.py", line 213, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/connection.py", line 982, in new
    return self.connection.clone()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/connection.py", line 626, in clone
    return self.__class__(**dict(self._info(resolve=False), **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/connection.py", line 636, in _info
    D = self.transport.default_connection_params
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/connection.py", line 906, in transport
    self._transport = self.create_transport()
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/connection.py", line 615, in create_transport
    return self.get_transport_cls()(client=self)
  File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.11-py3.6.egg/kombu/transport/redis.py", line 1044, in __init__
    raise ImportError('Missing redis library (pip install redis)')
ImportError: Missing redis library (pip install redis)
```

i did install redis through pip like request and redis-server on the machine, but nothing seems to work.

Any idea?

## Your Environment

* Version used: latest version
* Environment name and version (e.g. Chrome 39, python 3.5): python3.6
* Operating System and version (desktop or mobile): ubuntu 18

Thanks all

**Comment by rixx** [comment]
It appears you are using pretalx with an asynchronous task runner. In that case, redis is required for pretalx to function. If the supporting library says that you haven't installed `redis` and recommends `pip install redis`, then that is the correct solution – you may have installed redis with pip in the wrong environment. It needs to be installed in the same environment as pretalx.
